// <auto-generated />
using System;
using AlotiSoftware.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlotiSoftware.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200620225436_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlotiSoftware.Server.Data.Entities.BusinessUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Barrio");

                    b.Property<string>("Ciudad");

                    b.Property<int?>("ClientId");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("BusinessUnits");
                });

            modelBuilder.Entity("AlotiSoftware.Server.Data.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Document")
                        .HasMaxLength(20);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<int>("IDType");

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<int>("Rule");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AlotiSoftware.Server.Data.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId");

                    b.Property<DateTime?>("DateEnd");

                    b.Property<DateTime?>("DateInitial");

                    b.Property<string>("FilingOffice");

                    b.Property<int>("StateRequest");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("AlotiSoftware.Server.Data.Entities.BusinessUnit", b =>
                {
                    b.HasOne("AlotiSoftware.Server.Data.Entities.Client", "Client")
                        .WithMany("BusinessUnits")
                        .HasForeignKey("ClientId");
                });

            modelBuilder.Entity("AlotiSoftware.Server.Data.Entities.Request", b =>
                {
                    b.HasOne("AlotiSoftware.Server.Data.Entities.Client", "Client")
                        .WithMany("Requests")
                        .HasForeignKey("ClientId");
                });
#pragma warning restore 612, 618
        }
    }
}
